### ISSUE TITLE
Daily Sales Invoice report - Accounts Receivable Account incorrect data used

### ISSUE THREAD

**Issue by bkm888** [mntechnique/jmi_erpnext#39]
When running the new Daily Sales Invoice report, the "Accounts Receivable Account" column is currently being  populated with the Account header name form the ERPNext chart of accounts (Debtors - MSD). The instructions for this column were to force the value to always be "11000"

The external accounting program that is receiving the output of this report cannot parse the account header names of the ERPNext chart of accounts. It is also not appropriate for us to change the current chart of accounts to match the external program. We use the ERPNext chart of accounts in other places already.

Please force the data for this column to be the account number 11000

**Comment by ghost** [comment]
@bkm888 
As you requested in the mail, 'Accounts receivable' column should have the account number of the debit account.
We have done the same in the report, wherein if you put 'Account Number' in your 'Account' it will show up in the report the way you require it to be.

**Account number in  the account:**
![acc_no_edit](https://user-images.githubusercontent.com/29235673/39083741-3483b28e-4587-11e8-961d-e5559f54515d.png)

**This is how it will appear in the report:**
![acc_no_in_report](https://user-images.githubusercontent.com/29235673/39083756-91bbebb0-4587-11e8-8b30-5b9e2c450292.png)

To keep it update friendly, instead of hard-coding the value we have fetched the 'Account Number' from the debit account for 'Accounts Receivable' and its same for 'G/L account' wrt to line item being 'Item' or 'Tax'.

**Comment by bkm888** [comment]
In our version of ERPNext we elected to use the standard chart of accounts. There is no account number field visible on the account screen. See below:
![image](https://user-images.githubusercontent.com/30693364/39095347-1b988be2-460d-11e8-8707-afcd521e3726.png)


Is it still safe to click on the "Update Account Number" button if we elecetd the standart chart of accounts?

BKM

**Comment by ghost** [comment]
@bkm888 
Yes, it is safe to update the account number.
You can 'Update Account Number' and put your account number. This updated account number will be fetched in the report without having to hard-code it.
In your case, it will be '11000' for accounts receivable, and '40200' or '23100' for respective G/L account.
